apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: hydroflow
  labels:
    app: mosquitto
    app.kubernetes.io/part-of: hydroflow
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.207
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
