apiVersion: v1
kind: PersistentVolume
metadata:
  name: double-take-pv
  labels:
    app: double-take
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/frigate/double-take
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [k3frigate]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: double-take
  namespace: frigate
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  selector:
    matchLabels:
      app: double-take
