apiVersion: apps/v1
kind: Deployment
metadata:
  name: compreface-fe
  namespace: face-recognition
spec:
  replicas: 1
  selector: { matchLabels: { app: compreface-fe } }
  template:
    metadata: { labels: { app: compreface-fe } }
    spec:
      nodeSelector: { kubernetes.io/hostname: k3frigate }
      containers:
        - name: fe
          image: exadel/compreface-fe:1.2.0
          ports: [{ containerPort: 80, name: http }]
          env:
            - { name: APP_URL, value: http://compreface-admin:8080 }
            - { name: API_URL, value: http://compreface-api:8080 }
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 200m, memory: 128Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-fe
  namespace: face-recognition
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.212
  selector: { app: compreface-fe }
  ports: [{ port: 80, targetPort: http, name: http }]
