apiVersion: v1
kind: ConfigMap
metadata:
  name: chickenflow-config
  namespace: chickenflow
data:
  CAPTURES_DIR: /data/captures
  COOP_TZ: Europe/Sofia
  FRIGATE_COOP_CAM: cam01
  FRIGATE_URL: http://192.168.100.209:5000
  MQTT_URL: mqtt://mosquitto.hydroflow.svc.cluster.local:1883
  OLLAMA_MODEL: qwen3:4b-instruct-2507-q4_K_M
  OLLAMA_URL: http://ollama.chickenflow.svc.cluster.local:11434
  PORT: "4000"
