apiVersion: v1
kind: Service
metadata:
  name: chickenflow-postgres
  namespace: chickenflow
  labels:
    app: chickenflow-postgres
spec:
  type: ClusterIP
  selector:
    app: chickenflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: chickenflow-svc
  namespace: chickenflow
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.211
spec:
  type: LoadBalancer
  selector:
    app: chickenflow
  ports:
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
    - name: ws
      port: 4000
      targetPort: 4000
      protocol: TCP
