apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data-pv
  labels:
    app: gitea
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/frigate/gitea
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3frigate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
